export const FIRST_REQUIRED = 'First name is mandatory for registration';
export const ALPHABET_ONLY = 'Only alphabets are accepted';
export const MIN_REQUIRED = 'Min length of ';
export const MAX_REQUIRED = ' characters and max of ';
export const EXTRA_VALUE = ' characters are accepted';
export const ROLE_REQUIRED = 'Role is mandatory for registration';
export const LAST_REQUIRED = 'Last name is mandatory for registration';
export const EMAIL_REQUIRED = 'Email ID is mandatory for registration'
export const PASSWORD_REQUIRED = 'Password is mandatory for registration'
export const PASSWORD_MISMATCH = 'Password mistmatch';
export const PASSWORD_ENTER = 'Enter password';
export const EMAIL_VALID = 'Please enter a valid Email Address'
export const PASSWORD_ACCEPT = 'Password should contain only alphabets and numbers and are accepted';
export const PASSWORD_VAILD = 'Password should contain at least one letter and one number';
export const THERAPIST_REQUIRED="Associated Therapist is mandatory for registration";
export const PURPOSE_INVALID="Only alphabets, numbers and special characters are accepted as input";
export const USERNAME_REQUIRED = 'User name is mandatory for registration';
